<?php

$db = new PDO('mysql:host=localhost;dbname=train;charset=utf8', 'root', 'root');
$req = "SELECT * FROM user ";
$recupererstmt=$db->prepare($req);
$recupererstmt->execute();
$result=$recupererstmt->fetchAll();



?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>crud</title>
</head>
<body>  
<body>
    <table></table>
  <div class="container"></div>
<h1>Liste des utlisateurs</h1>
<table>
    <thead>
        <th>ID</th>
        <th>Nom</th>
        <th>password</th>
        <th>role</th>
       
    </thead>
    <tbody>
    <?php
        foreach($result as $user){
    ?>
            <tr>
                <td><?= $user['id'] ?></td>
                <td><?= $user['name'] ?></td>
                <td><?= $user['password'] ?></td>
                <td><?= $user['role'] ?></td>
                
            </tr>
    <?php
        }
    ?>
    </tbody>
</table>
<a href="add.php" class="btn btn-success">Ajouter</a>
<a href="add.php" class="btn btn-danger">supprimer</a>
</body>
</html>
</body>
</html>