<?php

$db = new PDO('mysql:host=localhost;dbname=train;charset=utf8', 'root', 'root');
$req = "SELECT * FROM user ";
$recupererstmt=$db->prepare($req);
$recupererstmt->execute();
$result=$recupererstmt->fetchAll();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>crud</title>
</head>
<body>  
<body>
<table class="table caption-top">
  <caption>List of users</caption>
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Password</th>
      <th scope="col">Role</th>
    </tr>


  <?php
        foreach($result as $user){
    ?>
            <tr>
                <tr><?= $user['id'] ?></tr>
                <tr><?= $user['name'] ?></tr>
                <tr><?= $user['password'] ?></tr>
                <tr><?= $user['role'] ?></tr>
                
            </th>
    <?php
        }
    ?>
    </tbody>
  </tbody>
</table>
<a href="add.php" class="btn btn-success">Ajouter</a>

</body>
</html>
</body>
</html>

