<?php
$db = new PDO('mysql:host=localhost;dbname=train;charset=utf8', 'root', 'root');
$req = "SELECT * FROM user ";
$recupererstmt=$db->prepare($req);
$recupererstmt->execute();
$result=$recupererstmt->fetchAll();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>crud</title>
</head>
<body>  
<div class="container">
<table class="table caption-top">
  <h1 class="text-center">List of users</h1>
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
   
      <th scope="col">Role</th>
    </tr>
  <?php
        foreach($result as $user){
    ?>
            <tr>
                <td><?= $user['id'] ?></td>
                <td><?= $user['name'] ?></td>
                
                <td><?= $user['role'] ?></td>
                <td><a  class="btn btn-success" href=""<?= $user['id'] ?>">Modifier</a> <a class="btn btn-danger" href="delete.php?id=<?= $user['id'] ?>">Supprimer</a></td>
                </tr>
                
            </th>
    <?php
        }
    ?>
    </tbody>
  </tbody>
</table>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
  Ajouter user>
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
  
</body>
</html>
</body>
</html>

