<?php
$db = new PDO('mysql:host=localhost;dbname=train;charset=utf8', 'root', 'root');
$req = "SELECT * FROM user ";
$recupererstmt=$db->prepare($req);
$recupererstmt->execute();
$result=$recupererstmt->fetchAll();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
    <title>crud</title>
</head>
<body>  
<div class="container">
<table class="table caption-top">
  <h1 class="text-center">List of users</h1>
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Role</th>
      <th scope="col">Action</th>
      
    </tr>
  <?php
        foreach($result as $user){
    ?>
            <tr>
                <td><?= $user['id'] ?></td>
                <td><?= $user['name'] ?></td>
                
                <td><?= $user['role'] ?></td>
                <td><a  class="btn btn-success" href="./../crud/modifiercrud.php?iduser=<?php = $user['id'] ?>">Modifier</a><a class="btn btn-danger" href="delete.php?id=<?= $user['id'] ?>">Supprimer</a></td>
                </tr>
                
            </th>
    <?php
        }
    ?>
    </tbody>
  </tbody>
</table>
  <a  class="btn btn-primary" href="./../crud/ajoutercrud.php">Ajouter un user</a>
<script src="https://kit.fontawesome.com/31149d48b0.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>



</body>
</html>
</body>
</html>

