<?php

$db = new PDO('mysql:host=localhost;dbname=train;charset=utf8', 'root', 'root');
$req = "SELECT * FROM user ";
$recupererstmt=$db->prepare($req);
$recupererstmt->execute();
$result=$recupererstmt->fetchAll();



?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>crud</title>
</head>
<body>  
<body>

<h1>Liste des produits</h1>
<table>
    <thead>
        <th>ID</th>
        <th>Nom</th>
        <th>password</th>
        <th>role</th>
       
    </thead>
    <tbody>
    <?php
        foreach($result as $user){
    ?>
            <tr>
                <td><?= $user['id'] ?></td>
                <td><?= $produit['name'] ?></td>
                <td><?= $produit['password'] ?></td>
                <td><?= $produit['role'] ?></td>
                
            </tr>
    <?php
        }
    ?>
    </tbody>
</table>
<a href="add.php">Ajouter</a>
</body>
</html>
</body>
</html>