<?php
session_start();
include("nav.phtml");
if (!isset($_SESSION['user'])) {
  header('Location:view/connection.phtml');
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="style.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>
  <h1>Bienvenue
    <?php echo $_SESSION['user']['name'] ?>
</h1>
 <?php foreach ($messages as $message):?>
  <div class="container">
  <div class="card mt-3">
              <div class="card-header d-flex justify-content-between p-3">
                <p class="fw-bold mb-0"><?php echo $message['name']?></p>
                <p class="text-muted small mb-0"><i class="far fa-clock"></i><?php echo $message['createdAt']?></p>
              </div>
              <div class="card-body ">
                <p class="mb-0">
                  <?php echo $message['content']?>
                <?php
                if (isset($_SESSION['user']['id']) && ($_SESSION['user']['id']) == $message['user_id']) {
                  echo ' <a href="./../delete.php?messageid=' . $message['id'] . '"class="btn btn-danger  ">Delete</a> ';
                  echo ' <a href="./../edit.php?messageId=' . $message['id'] . '"class="btn btn-success">Edit</a> ';
                }
                ?>
                </p>
              </div>
            </div>
</div>
<?php endforeach; ?>
<div class="container">
<form action="./../sending.php" method="POST">
<div class="flex-grow-0 py-3 px-4 border-top">
						<div class="input-group">
							<input type="text" class="form-control" placeholder="Type your message" name='content'>
							<button class="btn btn-primary" name="submit" >Send</button>
						</div>
</div>
</form>
</div>
  
<nav> 
     <ul class="pagination justify-content-center"> 
      <!-- Lien vers la page précédente (désactivé si on se trouve sur la 1ère page) -->
      <li class="page-item <?=($currentPage == 1) ? "disabled" : "" ?>">
        <a href="?page=<?= $currentPage - 1 ?>" class="page-link">Précédente</a>
      </li>
      <?php for ($page = 1; $page <= $nbpage; $page++): ?>
        <!-- Lien vers chacune des pages (activé si on se trouve sur la page correspondante) -->
         <li class="page-item <?=($currentPage == $page) ? "active" : "" ?>">
          <a href="?page=<?= $page ?>" class="page-link">
            <?= $page ?> 
          </a>
        </li>
      <?php endfor ?>
      <!-- Lien vers la page suivante (désactivé si on se trouve sur la dernière page) -->
      <li class="page-item <?=($currentPage == $nbpage) ? "disabled" : "" ?>">
        <a href="?page=<?= $currentPage + 1 ?>" class="page-link">Suivante</a>
      </li>
    </ul>
  </nav> 




</body>
</html>
<style>

body{
    background-image: url("./../images/IMG_9800.JPG");
}
</style>