<?php
session_start();
include("nav.phtml");
if (!isset($_SESSION['user'])) {
  header('Location:view/connection.phtml');
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="style.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>
  <h1>Bienvenue
    <?php echo $_SESSION['user']['name'] ?>
</h1>
 <?php foreach ($messages as $message):?>
  <div class="container">
  <div class="card">
              <div class="card-header d-flex justify-content-between p-3">
                <p class="fw-bold mb-0"><?php echo $message['name']?></p>
                <p class="text-muted small mb-0"><i class="far fa-clock"></i><?php echo $message['createdAt']?></p>
              </div>
              <div class="card-body">
                <p class="mb-0">
                  <?php echo $message['content']?>
                <?php
                if (isset($_SESSION['user']['id']) && ($_SESSION['user']['id']) == $message['user_id']) {
                  echo ' <a href="./../delete.php?messageid=' . $message['id'] . '"class="btn btn-danger">Delete</a> ';
                  echo ' <a href="./../edit.php?messageId=' . $message['id'] . '"class="btn btn-success">Edit</a> ';
                }
                ?>
                </p>
              </div>
            </div>
          



</div>

<?php endforeach; ?>





</body>