<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>


<header class="page-header">
  <div class="container ">
    <h2>tchat</h2>
  </div>
</header>
<div class="main">
  <div class="container ">
    <div class="chat-log">
      <div class="chat-log__item">
        <h3 class="chat-log__author"> <small></small></h3>
        <div class="chat-log__message"></div>
      </div>
      <div class="chat-log__item chat-log__item--own">
        <h3 class="chat-log__author"> <small></small></h3>
        <div class="chat-log__message"></div>
      </div>
    </div>
  </div>
  <div class="chat-form">
    <div class="container ">
      <form class="form-horizontal">
        <div class="row">
          <div class="col-sm-10 col-xs-8">
            <input type="text" class="form-control" id="" placeholder="Message" />
          </div>
          <div class="col-sm-2 col-xs-4">
            <button type="submit" class="btn btn-success btn-block">Send</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
</html>