<?php
session_start();
include("nav.phtml");
if (!isset($_SESSION['user'])) {
  header('Location:view/connection.phtml');

}

?>

<H1>Bienvenue
  <?php echo $_SESSION['user']['name'] ?>
</H1>


<?php


try {
  $db = new PDO('mysql:host=localhost;dbname=train;charset=utf8', 'root', 'root');
} catch (Exception $e) {
}

$sql = "SELECT u.name,m.content,m.createdAt,m.user_id
        FROM messages m 
        JOIN user u ON m.user_id= u.id";


$messageStatement = $db->prepare($sql);

$messageStatement->execute();

$messages = $messageStatement->fetchAll();

foreach ($messages as $message) {
  

  // echo "<tr>";
  // echo "<td>" . $message['name'] . "</td></br>
  //                  <td>" . $message['content'] . "</td></br>
  //                  <td>" . $message['createdAt'] . "</td></br>";

  // echo "</tr>";

     
  
$string =  '<li class="p-2">'.
'               <a href="#!" class="d-flex justify-content-between">'.
'                 <div class="d-flex flex-row">'.
                 
'                   <div class="pt-1">'.
'                     <p> '.$message['name'].'</p>'.
'                     <p class="small text-muted">'.$message['content'].'</p>'.
'                   </div>'.
'                 </div>'.
'                 <div class="pt-1">'.
'                   <p class="small text-muted mb-1">'.$message['createdAt'].'</p>'.
'                   <span class="text-muted float-end"><i class="fas fa-check" aria-hidden="true"></i></span>'.
'                 </div>'.
'               </a>'.
'             </li>'.
'           </ul>';

 echo $string; 


}



?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="train/style.css">
  <title>Document</title>

</head>

<body>

  <div class="container">
    <form action="./../chat.php" method="POST">
      <div class="chat-form">
        <div class="container ">
          <form class="form-horizontal">
            <div class="row">
              <div class="col-sm-10 col-xs-8">
                <input type="text" class="form-control" id="" placeholder="Message" />
              </div>
              <div class="col-sm-2 col-xs-4">
                <button type="submit" class="btn btn-success btn-block" name="submit">Send</button>
              </div>

            </div>
          </form>
        </div>
      </div>
  </div>
  </div>



</body>

</html>