<?php
session_start();
include("nav.phtml");
if (!isset($_SESSION['user'])) {
  header('Location:view/connection.phtml');

}

?>

<H1>Bienvenue
  <?php echo $_SESSION['user']['name'] ?>
</H1>


<?php


try {
  $db = new PDO('mysql:host=localhost;dbname=train;charset=utf8', 'root', 'root');
} catch (Exception $e) {
}

$sql = "SELECT u.name,m.content,m.createdAt,m.user_id
        FROM messages m 
        JOIN user u ON m.user_id= u.id";


$messageStatement = $db->prepare($sql);

$messageStatement->execute();

$messages = $messageStatement->fetchAll();

foreach ($messages as $message) {


  // echo "<tr>";
  // echo "<td>" . $message['name'] . "</td></br>
  //                  <td>" . $message['content'] . "</td></br>
  //                  <td>" . $message['createdAt'] . "</td></br>";

  // echo "</tr>";



  $string =

    '                 <div class="hello">' .
    '<img src="/w3images/bandmember.jpg" alt="Avatar">' .
    '                     <p> ' . $message['name'] . '</p>' .
    '                     <p >' . $message['content'] . '</p>' .
    ' <span class="time-right">' . $message['createdAt'] . '</span>' .
    ';'



    

  echo $string;


}



?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="train/style.css">
  <title>Document</title>

</head>

<body>

  <div class="container">
    <form action="" method="POST">
      <div class="chat-form">
        <div class="container ">
          <form class="form-horizontal">
            <div class="row">
              <div class="col-sm-10 col-xs-8">
                <input type="text" class="form-control" id="" placeholder="Message" />
              </div>
              <div class="col-sm-2 col-xs-4">
                <button type="submit" class="btn btn-success btn-block" name="submit">Send</button>
              </div>
            </div>
          </form>
        </div>
      </div>
  </div>
  </div>



</body>

</html>

<style>
  body {

    background-color: whitesmoke;
  }

  /* Chat containers */
  .hello {
    border: 2px solid #dedede;
    background-color: #f1f1f1;
    border-radius: 5px;
    padding: 10px;
    margin: 10px 0;
  }

  /* Darker chat container */
  .darker {
    border-color: #ccc;
    background-color: #ddd;
  }

  /* Clear floats */
  .container::after {
    content: "";
    clear: both;
    display: table;
  }

  /* Style images */
  .container img {
    float: left;
    max-width: 60px;
    width: 100%;
    margin-right: 20px;
    border-radius: 50%;
  }

  /* Style the right image */
  .container img.right {
    float: right;
    margin-left: 20px;
    margin-right: 0;
  }

  /* Style time text */
  .time-right {
    float: right;
    color: #aaa;
  }

  /* Style time text */
  .time-left {
    float: left;
    color: #999;
  }
</style>