<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Untitled</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/style.css">
</head>
<body>
     <?php
     
     $user1 = 1;
     $success = 0;
        if($user1)
        echo '<div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Ohh no Sorry </strong>User already exist<button type ="button" class ="close">
        <span aria-hidden="true">&times;</span></button>
        </div>';
     ?>

    <div class="register-photo">
        <div class="form-container">
            <div class="image-holder"></div>
            <form action="./inscription.php" method="POST">
                <h2 class="text-center"><strong>Create</strong> an account.</h2>
                <div class="form-group"><input class="form-control" type="text" required="required" name="name" placeholder="enter a username"></div>

                <div class="form-group"><input class="form-control" type="password"required="required" name="password" placeholder="Password"></div>

                <div class="form-group"><input class="form-control" type="password"required="required" name="password2" placeholder="Confirmer votre mot de passe"></div>
              
                <div class="form-group">
                    <div class="form-check"><label class="form-check-label"><input class="form-check-input" type="checkbox">I agree to the license terms.</label></div>
                </div>
                <div class="form-group"><button class="btn btn-primary btn-block" type="submit"  name="register">Sign Up</button></div><a href="view/connection.phtml" class="already">You already have an account? Login here.</a></form>

                
  
        </div>


    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
</body>

</html>

<style>
.register-photo {
  background:white;
  padding:80px 0;
}

.register-photo .image-holder {
  display:table-cell;
  width:auto;
  background-image:url("./../images/gettyimages-1264170591-612x612.jpeg");
 
}

.register-photo .form-container {
  display:table;
  max-width:900px;
  width:120;
  margin:0 auto;
  box-shadow:1px 1px 5px rgba(0,0,0,0.1);
}

.register-photo form {
  display:table-cell;
  width:400px;
  background-color:#ffffff;
  padding:40px 60px;
  color:#505e6c;
}

@media (max-width:991px) {
  .register-photo form {
    padding:40px;
  }
}

.register-photo form h2 {
  font-size:24px;
  line-height:1.5;
  margin-bottom:30px;
}

.register-photo form .form-control {
  background:#f7f9fc;
  border:none;
  border-bottom:1px solid #dfe7f1;
  border-radius:0;
  box-shadow:none;
  outline:none;
  color:inherit;
  text-indent:6px;
  height:40px;
}

.register-photo form .form-check {
  font-size:13px;
  line-height:20px;
}

.register-photo form .btn-primary {
  background:#f4476b;
  border:none;
  border-radius:4px;
  padding:11px;
  box-shadow:none;
  margin-top:35px;
  text-shadow:none;
  outline:none !important;
}

.register-photo form .btn-primary:hover, .register-photo form .btn-primary:active {
  background:#eb3b60;
}

.register-photo form .btn-primary:active {
  transform:translateY(1px);
}

.register-photo form .already {
  display:block;
  text-align:center;
  font-size:12px;
  color:#6f7a85;
  opacity:0.9;
  text-decoration:none;
}




</style>































<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inscription</title>
</head>

<body>


    <div class="container">

        <form action="./inscription.php" method="POST">
        <p class="message_error"></p>
        <?php
       
      if (isset($warning)) {
          echo "$warning";
      }
         ?>
        </p>
            <input type="text" name="name" placeholder="enter your name">
            <input type="password" name="password" placeholder="create password">

            <button type="submit" name="register" class="btn btn-primary">INSCRIVER VOUS</button>



        </form>


    </div>

</body>

</html>
<style>
  .message_error{

    color:red;
  }
   
</style> -->