<?php
session_start();
include("nav.phtml");
if (!isset($_SESSION['user'])) {
    header('Location:view/connection.phtml');
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>
    <html lang="fr">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Mon profil</title>

        <head>

        <body>
            <h2>Voici Votre Profile <?php echo $_SESSION['user']['name'] ?></h2>
            <div>Quelques informations sur vous : </div>
            <ul>

                <div class="container">
                    <form action="" method="post">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" name="name"
                            value="<?php echo $_SESSION['user']['name'] ?>" ;>
                        <div class="envoyer">
                            <button type="submit" class="btn btn-primary" name="modifiermonprenom">Modifier mon
                                prenom</button>
                        </div>
                    </form>
                </div>
                <?php
                if (isset($_POST['modifiermonprenom'])) {
                    if (isset($_SESSION['user']['name'])) {
                        $name = $_SESSION['user']['name'];
                        $db = new PDO('mysql:host=localhost;dbname=train;charset=utf8', 'root', 'root');
                        $data = [
                            'name' => $name,
                        ];
                        $sql = "UPDATE user SET name=:name  WHERE id=".$_SESSION['user']['id']."";
                        $stmt = $db->prepare($sql);
                        $stmt->execute($data);
                        $result

                        //     $db = new PDO('mysql:host=localhost;dbname=train;charset=utf8', 'root', 'root');
                        //     $change = $db->prepare( " UPDATE  user SET name = ? WHERE id = ". $_SESSION['user']['id'] . "");
                        //     $change->execute(
                        //         array(
                        //             ':name' => $name,
                        //         )
                        //     );
                    }
                    // var_dump($change);
                }
                ?>
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
                    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
                    crossorigin="anonymous"></script>
        </body>

    </html>