<?php
session_start();
include("nav.phtml");
if (!isset($_SESSION['user'])) {
    header('Location:view/connection.phtml');
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>
    <html lang="fr">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Mon profil</title>
        <head>
        <body>
            <h2 class ="text-center m-3">  Mon Profile </h2>
          
            
              <form action="" method="post">
                <div class="container">
                    
                        <label for="name" class="form-label"><strong>Name</strong></label>
                        <input type="text" class="form-control" name="name"
                            value="<?php echo $_SESSION['user']['name'] ?>" ;>

                            <label for="email" class="form-label"><strong>email</strong></label>
                        <input type="text" class="form-control" name="email"
                            value="<?php echo $_SESSION['user']['Email'] ?>" ;>
                        <div class="envoyer mt-3">
                            <button type="submit" class="btn btn-success" name="modifiermonprenom">Modifier mon
                                prenom</button>
                        </div>
                    </form>
                </div>
                <?php
                if (isset($_POST['modifiermonprenom'])) {
                    if (isset($_SESSION['user']['name']) && isset($_SESSION['user']['email'])) {
                        $email=$_POST['email'];
                        $name = $_POST['name'];
                        $db = new PDO('mysql:host=localhost;dbname=train;charset=utf8', 'root', 'root');
                        $change = $db->prepare(" UPDATE  user SET name = :name WHERE id = " . $_SESSION['user']['id'] . "");
                        $change->execute(
                            array(
                                ':name' => $name,
                                'Email'=>$email,
                            )
                        );
                    }
                    session_destroy();
                    header('location:./view/connection.phtml');
                    exit();

                }
                ?>
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
                    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
                    crossorigin="anonymous"></script>
        </body>

    </html>