<?php

session_start();
include("nav.phtml");


?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<html lang="fr">
  <head>
    <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mon profil</title>
 <head>
  <body>
   <h2>Voici le profil de <?php  echo $_SESSION['Name'] ?></h2>
    <div>Quelques informations sur vous : </div>
    <ul>
      <li>Votre id est : <?php echo  $profil['id'] ?></li>
      <li>Votre nom est : <?php  echo $profil['name'] ?></li>
      
     
</html>
</body>
</html>