<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="train/style.css">
  <title>Document</title>

</head>

<body>

  <?php

include("./../welcome.php");
?>
    <div class="container m-5">

  <div class="hello">
    <form action="./../sending.php" method="POST">
      <div class="chat-form">
        <div class="container">
          <form class="form-horizontal">
            <div class="row">
              <div class="col-sm-10 col-xs-8">


                <input type="text" class="form-control" id="" placeholder="Message" name='content' />
              </div>

              <div class="col-sm-2 col-xs-4">
                <button type="submit" class="btn btn-success btn-block" name="submit">Send</button>
              </div>
            </div>
          </form>


        </div>
      </div>
  </div>`
  </div>
</div>
  <nav>
    <ul class="pagination justify-content-center">
      <!-- Lien vers la page précédente (désactivé si on se trouve sur la 1ère page) -->
      <li class="page-item <?=($currentPage == 1) ? "disabled" : "" ?>">
        <a href="?page=<?= $currentPage - 1 ?>" class="page-link">Précédente</a>
      </li>
      <?php for ($page = 1; $page <= $nbpage; $page++): ?>
      <!-- Lien vers chacune des pages (activé si on se trouve sur la page correspondante) -->
      <li class="page-item <?=($currentPage == $page) ? "active" : "" ?>">
        <a href="?page=<?= $page ?>" class="page-link"><?= $page ?></a>
      </li>
      <?php endfor ?>
      <!-- Lien vers la page suivante (désactivé si on se trouve sur la dernière page) -->
      <li class="page-item <?=($currentPage == $nbpage) ? "disabled" : "" ?>">
        <a href="?page=<?= $currentPage + 1 ?>" class="page-link">Suivante</a>
      </li>
    </ul>
  </nav>



</body>

</html>

<style>
  body {

    background-color: whitesmoke;
  }

  /* Chat containers */
  .container {
    border: 2px solid #dedede;
    background-color: #f1f1f1;
    border-radius: 5px;
    padding: 10px;
    margin: 10px 0;
  }

  /* Darker chat container */
  .darker {
    border-color: #ccc;
    background-color: #ddd;
  }

  /* Clear floats */
  .container::after {
    content: "";
    clear: both;
    display: table;
  }

  /* Style images */
  .container img {
    float: left;
    max-width: 60px;
    width: 100%;
    margin-right: 20px;
    border-radius: 50%;
  }

  /* Style the right image */
  .container img.right {
    float: right;
    margin-left: 20px;
    margin-right: 0;
  }

  /* Style time text */
  .time-right {
    float: right;
    color: #aaa;
  }

  /* Style time text */
  .time-left {
    float: left;
    color: #999;
  }

  body {
    background-image: url("./../images/IMG_9800.JPG");
  .page-header {
    background: #006A4E;
    margin: 0;
    padding: 20px 0 10px;
    color: #FFFFFF;
    position: fixed;
    width: 100%;
    z-index: 1
  }

  .main {
    height: 100vh;
    padding-top: 70px;
  }

  .chat-log {
    padding: 40px 0 114px;
    height: auto;
    overflow: auto;
  }

  .chat-log__item {
    background: #fafafa;
    padding: 30px;
    margin: 0 auto 20px;
    max-width: 80%;
    float: left;
    border-radius: 4px;
    box-shadow: 0 1px 2px rgba(0, 0, 0, .1);
    clear: both;
  }

  .chat-log__item.chat-log__item--own {
    float: right;
    background: #DCF8C6;
    text-align: right;
   
  }

  .chat-form {
    background: #DDDDDD;
    padding: 20px ;
    position: fixed;
    bottom: 0;
    width: 100%;
  }

  .chat-log__author {
    margin: 0 auto .5em;
    font-size: 20px;
    font-weight: bold;
  }


</style>